# Generated by Django 2.2.1 on 2019-05-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bathroom',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bedroom',
            new_name='bedrooms',
        ),
    ]
