# Generated by Django 2.2.1 on 2019-05-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190520_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thumbnail',
            new_name='ProductImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile'),
        ),
    ]
