# Generated by Django 2.2.1 on 2019-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190525_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property_for',
        ),
        migrations.AddField(
            model_name='product',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bedroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('For ShortLet', 'For ShortLet')], default='For Rent', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='parking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
