# Generated by Django 2.2.1 on 2019-06-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
