# Generated by Django 2.2.1 on 2019-06-16 22:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='property-for-sale-or-for-rent'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='media',
            field=models.ImageField(height_field='height', null=True, upload_to=products.models.media_location, validators=[products.models.image_validation], width_field='width'),
        ),
    ]
