# Generated by Django 2.2.1 on 2019-06-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20190617_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
