# Generated by Django 2.2.1 on 2019-06-18 10:18

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20190618_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='media',
            field=models.ImageField(blank=True, default=1, height_field='height', null=True, upload_to=products.models.media_location, validators=[products.models.image_validation], width_field='width'),
        ),
    ]
