# Generated by Django 2.2.1 on 2019-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190618_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='width',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='media',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
