# Generated by Django 2.2.1 on 2019-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20190618_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
