# Generated by Django 2.2.1 on 2019-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20190618_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
