# Generated by Django 2.2.1 on 2019-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True),
        ),
    ]
