# Generated by Django 2.2.1 on 2019-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20190624_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-boosted', '-timestamp', '-title']},
        ),
        migrations.AddField(
            model_name='product',
            name='patio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment/Flat'), ('Bungalow', 'Bungalow'), ('Duplex', 'Duplex'), ('Self Contain', 'Self Contain'), ('Office Space', 'Office Space'), ('Warehouse', 'Warehouse'), ('Filling Station', 'Filling Station'), ('Land', 'Land')], max_length=120),
        ),
    ]
