# Generated by Django 2.2.1 on 2019-07-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20190711_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='property-for-sale-or-for-rent'),
        ),
    ]
