# Generated by Django 2.2.1 on 2019-05-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
