# Generated by Django 2.2.1 on 2019-05-25 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190525_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_2',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid number', message='Please enter a valid phone number', regex='^[0-9]{11}$')]),
        ),
    ]
