# Generated by Django 2.2.1 on 2019-06-14 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_clientrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrequest',
            options={'ordering': ['-timestamp', '-ref']},
        ),
        migrations.RenameField(
            model_name='clientrequest',
            old_name='maximum_price',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='clientrequest',
            old_name='rid',
            new_name='ref',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='minimum_price',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='title',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='email',
            field=models.EmailField(default='dsix@yahoo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='i_am_an',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Agent', 'Agent')], default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='number_of_bedroom',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10+')], null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='phone_number',
            field=models.CharField(default='08033445412', max_length=11, validators=[django.core.validators.RegexValidator(code='invalid number', message='Please enter a valid phone number', regex='^[0-9]{11}$')]),
            preserve_default=False,
        ),
    ]
