# Generated by Django 2.2.1 on 2019-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190615_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='budget',
            field=models.CharField(max_length=120),
        ),
    ]
