# Generated by Django 2.2.1 on 2019-06-15 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190615_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='city',
            new_name='locality',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='property_type',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid number', message='Please enter a valid phone number', regex='^[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='name',
            field=models.CharField(default='James Bond', max_length=120),
            preserve_default=False,
        ),
    ]
