# Generated by Django 2.2.1 on 2019-06-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_mymessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uid',
            new_name='ref',
        ),
    ]
