# Generated by Django 2.2.1 on 2019-06-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190615_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_2',
            new_name='whatsapp',
        ),
    ]
