# Generated by Django 2.2.1 on 2019-06-16 22:47

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190615_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(height_field='height_field', null=True, upload_to=dashboard.models.image_upload_to_profile, validators=[dashboard.models.image_validation], width_field='width_field'),
        ),
    ]
