# Generated by Django 2.2.1 on 2019-06-26 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190616_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid number', message='Please enter a valid phone number', regex='^[0-9]{11}$')]),
        ),
    ]
