# Generated by Django 2.2.1 on 2019-07-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190626_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('subject', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('broadcast', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('trashed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='dashboard.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='dashboard.Profile')),
            ],
            options={
                'ordering': ['-timestamp', '-ref'],
            },
        ),
        migrations.DeleteModel(
            name='MyMessage',
        ),
    ]
