# Generated by Django 2.2.1 on 2019-07-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190701_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inbox',
            new_name='MyMessage',
        ),
    ]
