# Generated by Django 2.2.1 on 2019-07-11 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20190701_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Land', 'Land')], default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='bedroom',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='09088776655', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid number', message='Please enter a valid phone number', regex='^[0-9]{11}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(default='08099887766', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid number', message='Please enter a valid phone number', regex='^[0-9]{11}$')]),
            preserve_default=False,
        ),
    ]
