# Generated by Django 2.2.1 on 2019-07-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20190711_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='bedroom',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], null=True),
        ),
    ]
