# Generated by Django 2.2.1 on 2019-11-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20190711_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='bedroom',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6+')], null=True),
        ),
    ]
